// reducers always take two arguments: state and action
// state that gets passed here is only the state that was previously generated by the books reducer
// not the application state
// if the argument comes in and it's undefined, set it to null
export default function(state = null, action) {
  switch(action.type) {
    case 'BOOK_SELECTED':
      return action.payload;
  }
  return state;
}
